import { FriendlyStateEntity, Scene } from './home-assistant-api'

export const testOneFrom: FriendlyStateEntity = {
  entity: 'light.office_lamp_left',
  name: 'Office Lamp Left',
  state: {
    min_mireds: 153,
    max_mireds: 500,
    effect_list: ['None', 'candle', 'fire'],
    supported_color_modes: ['color_temp', 'xy'],
    mode: 'normal',
    dynamics: 'none',
    friendly_name: 'Office Lamp Left',
    supported_features: 44,
    color_mode: 'color_temp',
    brightness: 89,
    color_temp: 382,
    hs_color: [28.583, 68.442],
    rgb_color: [255, 163, 80],
    xy_color: [0.535, 0.388],
    effect: 'None',
    state: 'on',
  },
}

export const testOneTo: FriendlyStateEntity = {
  entity: 'light.office_lamp_left',
  name: 'Office Lamp Left',
  state: {
    min_mireds: 153,
    max_mireds: 500,
    effect_list: ['None', 'candle', 'fire'],
    supported_color_modes: ['color_temp', 'xy'],
    mode: 'normal',
    dynamics: 'none',
    friendly_name: 'Office Lamp Left',
    supported_features: 44,
    color_mode: 'color_temp',
    brightness: 250,
    color_temp: 196,
    hs_color: [27.12, 17.875],
    rgb_color: [255, 230, 209],
    xy_color: [0.368, 0.349],
    effect: 'None',
    state: 'on',
  },
}

export const testTwoFrom: FriendlyStateEntity = {
  entity: 'light.office_lamp_right',
  name: 'Office Lamp Right',
  state: {
    min_mireds: 153,
    max_mireds: 500,
    effect_list: ['None', 'candle', 'fire'],
    supported_color_modes: ['color_temp', 'xy'],
    mode: 'normal',
    dynamics: 'none',
    friendly_name: 'Office Lamp Right',
    supported_features: 44,
    color_mode: 'color_temp',
    brightness: 82,
    color_temp: 382,
    hs_color: [28.583, 68.442],
    rgb_color: [255, 163, 80],
    xy_color: [0.535, 0.388],
    effect: 'None',
    state: 'on',
  },
}

export const testTwoTo: FriendlyStateEntity = {
  entity: 'light.office_lamp_right',
  name: 'Office Lamp Right',
  state: {
    min_mireds: 153,
    max_mireds: 500,
    effect_list: ['None', 'candle', 'fire'],
    supported_color_modes: ['color_temp', 'xy'],
    mode: 'normal',
    dynamics: 'none',
    friendly_name: 'Office Lamp Right',
    supported_features: 44,
    color_mode: 'color_temp',
    brightness: 209,
    color_temp: 200,
    hs_color: [27.001, 19.243],
    rgb_color: [255, 228, 205],
    xy_color: [0.372, 0.35],
    effect: 'None',
    state: 'on',
  },
}

export const onOffTestFrom: FriendlyStateEntity = {
  entity: 'light.office_overhead_light',
  name: 'Overhead Light',
  state: {
    supported_color_modes: ['brightness'],
    friendly_name: 'Overhead Light',
    supported_features: 32,
    state: 'off',
  },
}

export const onOffTestTo: FriendlyStateEntity = {
  entity: 'light.office_overhead_light',
  name: 'Overhead Light',
  state: {
    supported_color_modes: ['brightness'],
    friendly_name: 'Overhead Light',
    supported_features: 32,
    color_mode: 'brightness',
    brightness: 181,
    state: 'on',
  },
}

export const testOneSceneFrom: Scene = {
  entity: 'scene.office_night',
  internalId: '1643228416807',
  name: 'Office Night',
  affects: {
    'light.office_lamp_left': {
      entity: 'light.office_lamp_left',
      name: 'Office Lamp Left',
      state: {
        min_mireds: 153,
        max_mireds: 500,
        effect_list: ['None', 'candle', 'fire'],
        supported_color_modes: ['color_temp', 'xy'],
        mode: 'normal',
        dynamics: 'none',
        friendly_name: 'Office Lamp Left',
        supported_features: 44,
        color_mode: 'color_temp',
        brightness: 89,
        color_temp: 382,
        hs_color: [28.583, 68.442],
        rgb_color: [255, 163, 80],
        xy_color: [0.535, 0.388],
        effect: 'None',
        state: 'on',
      },
    },
    'light.office_lamp_right': {
      entity: 'light.office_lamp_right',
      name: 'Office Lamp Right',
      state: {
        min_mireds: 153,
        max_mireds: 500,
        effect_list: ['None', 'candle', 'fire'],
        supported_color_modes: ['color_temp', 'xy'],
        mode: 'normal',
        dynamics: 'none',
        friendly_name: 'Office Lamp Right',
        supported_features: 44,
        color_mode: 'color_temp',
        brightness: 82,
        color_temp: 382,
        hs_color: [28.583, 68.442],
        rgb_color: [255, 163, 80],
        xy_color: [0.535, 0.388],
        effect: 'None',
        state: 'on',
      },
    },
    'light.office_overhead_light': {
      entity: 'light.office_overhead_light',
      name: 'Overhead Light',
      state: {
        supported_color_modes: ['brightness'],
        friendly_name: 'Overhead Light',
        supported_features: 32,
        state: 'off',
      },
    },
    'light.elgato_key_light': {
      entity: 'light.elgato_key_light',
      name: 'Elgato Key Light',
      state: {
        min_mireds: 143,
        max_mireds: 344,
        supported_color_modes: ['color_temp'],
        friendly_name: 'Elgato Key Light',
        supported_features: 0,
        state: 'off',
      },
    },
    'light.elgato_ring_light': {
      entity: 'light.elgato_ring_light',
      name: 'Elgato Ring Light',
      state: {
        min_mireds: 143,
        max_mireds: 344,
        supported_color_modes: ['color_temp'],
        friendly_name: 'Elgato Ring Light',
        supported_features: 0,
        state: 'off',
      },
    },
  },
}

export const testOneSceneTo: Scene = {
  entity: 'scene.office_day',
  internalId: '1655635182629',
  name: 'Office Day',
  affects: {
    'light.office_lamp_left': {
      entity: 'light.office_lamp_left',
      name: 'Office Lamp Left',
      state: {
        min_mireds: 153,
        max_mireds: 500,
        effect_list: ['None', 'candle', 'fire'],
        supported_color_modes: ['color_temp', 'xy'],
        mode: 'normal',
        dynamics: 'none',
        friendly_name: 'Office Lamp Left',
        supported_features: 44,
        color_mode: 'color_temp',
        brightness: 250,
        color_temp: 196,
        hs_color: [27.12, 17.875],
        rgb_color: [255, 230, 209],
        xy_color: [0.368, 0.349],
        effect: 'None',
        state: 'on',
      },
    },
    'light.office_lamp_right': {
      entity: 'light.office_lamp_right',
      name: 'Office Lamp Right',
      state: {
        min_mireds: 153,
        max_mireds: 500,
        effect_list: ['None', 'candle', 'fire'],
        supported_color_modes: ['color_temp', 'xy'],
        mode: 'normal',
        dynamics: 'none',
        friendly_name: 'Office Lamp Right',
        supported_features: 44,
        color_mode: 'color_temp',
        brightness: 209,
        color_temp: 200,
        hs_color: [27.001, 19.243],
        rgb_color: [255, 228, 205],
        xy_color: [0.372, 0.35],
        effect: 'None',
        state: 'on',
      },
    },
    'light.office_overhead_light': {
      entity: 'light.office_overhead_light',
      name: 'Overhead Light',
      state: {
        supported_color_modes: ['brightness'],
        friendly_name: 'Overhead Light',
        supported_features: 32,
        color_mode: 'brightness',
        brightness: 181,
        state: 'on',
      },
    },
  },
}
